# Generated by Django 5.1.7 on 2025-05-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
